### ISSUE TITLE
Did you change the webmidi.min.js file for Purr Data or do you use it as it is?

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/purr-data#4]
Hey @cuinjune,
I want to optimize the webMidi implementation I adapted for OF / ofxPd.
My question is: Do you use the original webmidi.min.js file or did you make some changes for using it with Pure Data.
I guess, if I want to use the current version I need to use cjs: https://github.com/djipco/webmidi/tree/master/dist/cjs ?
Best, Jonathan

**Comment by cuinjune** [comment]
Hi Jonathan, I just used the original webmidi.min.js file, I don't think I made any changes to the file.
